[package]
name = "clevis-pin-tpm2"
version = "0.1.0"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tss-esapi = "4.0.5-alpha.1"
serde = "1.0"
biscuit = "0.5.0-beta2"
serde_json = "1.0"
base64 = "0.12.1"
